# Ruta general
logger.ruta.general=/home/sergiopt/Repositorios/simple-java-logger/log.log

# Rutas por clase
logger.ruta.es.sergiopt.logger.Main=/home/sergiopt/Repositorios/simple-java-logger/main-log.log